server:
  port: 9090

spring:
  application:
    name: infinispan-cache
  cache:
    infinispan:
      config: classpath:infinispan.xml
    type:
      infinispan
    cache-names:
      - employee
      - employees
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
       cache: TRACE