server:
  port: 9090

spring:
  application:
    name: guava-cache-application

  cache:
    cache-names:
      - employee
      - employees
    type:
      guava
    guava:
      spec:
       - maximumSize=500
       - expireAfterAccess=600s
       - initialCapacity=100
       - recordStats
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

endpoints:
  caches:
    enabled: true

logging:
  level:
    org:
      springframework:
       cache: TRACE